In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("clustered_mall_customers.csv")
print(df.head())
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

   Age  Annual Income  Spending Score  Cluster
0   19             15              39        4
1   21             15              81        0
2   20             16               6        4
3   23             16              77        0
4   31             17              40        4


In [3]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [4]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(random_state=42)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

In [5]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
acc=accuracy_score(y_test,y_pred)
cm=confusion_matrix(y_test,y_pred)
cr=classification_report(y_test,y_pred)
print("Accuracy:",acc)
print("Confusion Matrix:",cm)
print("Classification Report:",cr)

Accuracy: 0.925
Confusion Matrix: [[14  2  0  0  0]
 [ 0  6  0  0  0]
 [ 0  0  5  0  0]
 [ 1  0  0  9  0]
 [ 0  0  0  0  3]]
Classification Report:               precision    recall  f1-score   support

           0       0.93      0.88      0.90        16
           1       0.75      1.00      0.86         6
           2       1.00      1.00      1.00         5
           3       1.00      0.90      0.95        10
           4       1.00      1.00      1.00         3

    accuracy                           0.93        40
   macro avg       0.94      0.96      0.94        40
weighted avg       0.94      0.93      0.93        40

